### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by alkersho** [halohalospecial/atom-elm-fu#163]
[Enter steps to reproduce:]

1. Changed record variables, warned about type mismatch in init function.
2. Changed the type to satisfy type change.
3. Saved the file and it threw this error.

linter still shows error but elm reactor is working fine.
reinstalling didn't solve the issue.

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Ubuntu 18.04.2
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 9.11.0

### Stack Trace

Uncaught TypeError: Cannot read property 'start' of undefined

```
At /home/omar/.atom/packages/elmjutsu/lib/elm-make-runner.js:769

TypeError: Cannot read property 'start' of undefined
    at /packages/elmjutsu/lib/elm-make-runner.js:769:56
    at Array.forEach (<anonymous>)
    at ElmMakeRunner.maybeShowInferredTypeAnnotations (/packages/elmjutsu/lib/elm-make-runner.js:765:10)
    at /packages/elmjutsu/lib/elm-make-runner.js:508:16
    at /packages/elmjutsu/lib/eval-helper.js:56:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
     -0:44 intentions:highlight (input.hidden-input)
  5x -0:43.9.0 editor:move-to-end-of-word (input.hidden-input)
     -0:42.7.0 core:select-up (input.hidden-input)
     -0:42.2.0 core:backspace (input.hidden-input)
     -0:42.1.0 intentions:highlight (input.hidden-input)
  3x -0:42 editor:delete-to-beginning-of-word (input.hidden-input)
     -0:39.6.0 autocomplete-plus:confirm (input.hidden-input)
  2x -0:37.2.0 core:backspace (input.hidden-input)
     -0:36.2.0 intentions:highlight (input.hidden-input)
     -0:36.1.0 core:save (input.hidden-input)
     -0:33.5.0 editor:newline (input.hidden-input)
  2x -0:31.9.0 intentions:highlight (input.hidden-input)
     -0:31.2.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -0:30.8.0 editor:newline (input.hidden-input)
     -0:30.7.0 intentions:highlight (input.hidden-input)
     -0:30.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-python-virtualenv 1.0.2 
autocomplete-paths 2.12.2 
autocomplete-python 1.14.0 
busy-signal 2.0.1 
elmjutsu 9.11.0 
emmet 2.4.3 
file-icons 2.1.31 
git-plus 8.6.2 
highlight-selected 0.15.0 
intentions 1.1.5 
language-elm 1.5.0 
linter 2.3.0 
linter-ui-default 1.7.1 
remote-edit-ni 3.5.1 
scroll-marker 0.3.2 
```

**Comment by SidneyNemzer** [comment]
Temporary fix: It's related to inferring type annotations, disable that setting and you'll stop getting the error.
