### ISSUE TITLE
failed  to load elmjitsu unsafe eval

### ISSUE THREAD

**Issue by ta3pks** [halohalospecial/atom-elm-fu#166]
```
atom version:1.36
```
When i try to install elmjitsu i keep getting this error
```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
```

**Comment by tofusoul** [comment]
I have the same issue

full error message: 

```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
    at Function.wrapfunction [as function] (/home/tofu/.atom/packages/elmjutsu/node_modules/depd/index.js:413:42)
    at Object.<anonymous> (/home/tofu/.atom/packages/elmjutsu/node_modules/body-parser/index.js:37:46)
    at Object.<anonymous> (/home/tofu/.atom/packages/elmjutsu/node_modules/body-parser/index.js:159:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/home/tofu/.atom/packages/elmjutsu/node_modules/express/lib/express.js:15:18)
    at Object.<anonymous> (/home/tofu/.atom/packages/elmjutsu/node_modules/express/lib/express.js:116:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/home/tofu/.atom/packages/elmjutsu/node_modules/express/index.js:11:18)
    at Object.<anonymous> (/home/tofu/.atom/packages/elmjutsu/node_modules/express/index.js:13:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/home/tofu/.atom/packages/elmjutsu/lib/hot-reloader.js:3:29)
    at Object.<anonymous> (/home/tofu/.atom/packages/elmjutsu/lib/hot-reloader.js:163:2)
```

**Comment by halohalospecial** [comment]
@NikosEfthias @tofusoul can you try unchecking `Enable Hot Reloading` in the Settings view?

**Comment by tofusoul** [comment]
Thanks @halohalospecial.  Hot reloading was unchecked. recent atom update in the arch repo seem to have fixed the error for me. Keep up the great work.
